### PR TITLE
Following issuer chain of modules to see if it's within the same depe…

### PR DESCRIPTION
**Pull request by derekmiranda**
…ndency tree as the build entry

- fixed bug where no images showed up in payload when using Webpack dependencies after Ad.js paradigm shift
- this check for image/font dependencies adds to the current checks

### CODE REVIEW

**Comment by derekmiranda** [comment]
- Will test with other ads to see if this breaks anything
- Also need to test when there's a circular dependency

**Comment by gmcdev** [comment]
@derekmiranda - confidence level on this merge?

**Comment by derekmiranda** [comment]
Pretty confident, it should just build upon current functionality. Only worried about encountering a loop in the module graph traversal if there's two modules that import each other

**Comment by gmcdev** [comment]
@derekmiranda please go ahead.

**Pull request merged**
